# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-06-14 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20170613_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='child',
        ),
        migrations.AddField(
            model_name='message',
            name='first_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_messages', to='chat.Message'),
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_message', to='chat.Message'),
        ),
    ]
